[control_plane]
kind1 ansible_host=136.118.187.177 internal_ip=10.138.0.3

[workers]
kind2 ansible_host=35.197.99.148 internal_ip=10.138.0.2
kind3 ansible_host=35.185.194.95 internal_ip=10.138.0.4

[kind_hosts:children]
control_plane
workers
